//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarecha_Spasial_Baru.Scripts {
    
    
    public partial class FullScreenVisual {
        
        /// <summary>
        /// WebFigureControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MathWorks.MATLAB.NET.WebFigures.Service.WebFigureControl WebFigureControl1;
    }
}
